name: tests

on: push

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: 1.26.3
      - run: go test ./...
  
  cli-build-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: 1.26.3
      - run: go build -ldflags="-w -s" ./cmd/mcutils
      - run: ./mcutils version
  
  srv-lookup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: 1.26.3
      - run: go build -ldflags="-w -s" ./cmd/mcutils
      - run: ./mcutils version
      # pinging mc.hypixel.net as it is known to work only with SRV lookup enabled and should be up for a long time coming
      - run: ./mcutils ping mc.hypixel.net 25565
  
  vanilla-ping-legacy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - 1.2.5
          - 1.4.7
          - 1.5.2
          - 1.6.4
          - 1.7.10
          - latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: 1.26.3
      - run: go build -ldflags="-w -s" ./cmd/mcutils
      - run: docker run --rm -d -e EULA=true -p 25565:25565 -e VERSION=${{ matrix.version }} --name test-minecraft-server itzg/minecraft-server
      - run: sleep 120
      - run: ./mcutils ping-legacy localhost 25565
      - run: docker stop test-minecraft-server
  
  vanilla-ping-legacy-1-6-4:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - 1.6.4
          - 1.7.10
          - latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: 1.26.3
      - run: go build -ldflags="-w -s" ./cmd/mcutils
      - run: docker run --rm -d -e EULA=true -p 25565:25565 -e VERSION=${{ matrix.version }} --name test-minecraft-server itzg/minecraft-server
      - run: sleep 120
      - run: ./mcutils ping-legacy-1.6.4 localhost 25565
      - run: docker stop test-minecraft-server
  
  vanilla-ping-slp:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - 1.7.10
          - latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: 1.26.3
      - run: go build -ldflags="-w -s" ./cmd/mcutils
      - run: docker run --rm -d -e EULA=true -p 25565:25565 -e VERSION=${{ matrix.version }} --name test-minecraft-server itzg/minecraft-server
      - run: sleep 120
      - run: ./mcutils ping localhost 25565
      - run: docker stop test-minecraft-server

  vanilla-query-basic:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - 1.2.5
          - 1.6.4
          - 1.7.10
          - latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: 1.26.3
      - run: go build -ldflags="-w -s" ./cmd/mcutils
      - run: docker run --rm -d -e EULA=true -p 25565:25565/udp -e VERSION=${{ matrix.version }} -e ENABLE_QUERY=true --name test-minecraft-server itzg/minecraft-server
      - run: sleep 120
      - run: ./mcutils query-basic localhost 25565
      - run: docker stop test-minecraft-server
  
  vanilla-query-full:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - 1.2.5
          - 1.6.4
          - 1.7.10
          - latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: 1.26.3
      - run: go build -ldflags="-w -s" ./cmd/mcutils
      - run: docker run --rm -d -e EULA=true -p 25565:25565/udp -e VERSION=${{ matrix.version }} -e ENABLE_QUERY=true --name test-minecraft-server itzg/minecraft-server
      - run: sleep 120
      - run: ./mcutils query-full localhost 25565
      - run: docker stop test-minecraft-server
  
  vanilla-rcon:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - 1.2.5
          - 1.6.4
          - 1.7.10
          - latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: 1.26.3
      - run: go build -ldflags="-w -s" ./cmd/mcutils
      - run: docker run --rm -d -e EULA=true -p 25565:25565 -e VERSION=${{ matrix.version }} -e RCON_PASSWORD=password --name test-minecraft-server itzg/minecraft-server
      - run: sleep 120
      - run: ./mcutils rcon localhost 25575 password "say hello"
      - run: docker stop test-minecraft-server